import type { SiteConfig, SiteContent } from "../types";

export const SITE_CONFIG: SiteConfig = {
  title: "Eashan M. Joshi",
  author: "Eashan M. Joshi",
  description:
    "Software Engineer and AI researcher building intelligent, high-performance systems—from multi-agent LLM platforms and RAG pipelines to cloud-native fintech backends.",
  lang: "en",
  siteLogo: "/eashan-small.jpg",
  navLinks: [
    { text: "About", href: "#about" },
    {
      text: "Resume",
      href: "/Eashan_Joshi_Resume.pdf",
      external: true,
    },
    { text: "Experience", href: "#experience" },
    { text: "Projects", href: "#projects" },
    { text: "Skills", href: "#skills" },
    { text: "Contact", href: "#lets-connect" },
  ],
  socialLinks: [
    { text: "LinkedIn", href: "https://www.linkedin.com/in/eashanjoshi/" },
    { text: "Github", href: "https://github.com/EashanJoshi" },
    { text: "Instagram", href: "https://www.instagram.com/eashan_joshi11/" },
  ],
  socialImage: "/eashan-og.png",
  canonicalURL: "https://eashan-m-joshi.vercel.app",
};

export const SITE_CONTENT: SiteContent = {
  hero: {
    name: "Eashan M. Joshi",
    specialty: "Senior Software Engineer",
    summary:
      "Software Engineer and AI builder with deep expertise in LLMs, multi-agent systems, and cloud-native backends. I ship intelligent products—from CodeIntellect’s multi-agent debugging lab to production fintech systems—and train for endurance outside the terminal.",
    email: "eashan.m.joshi@gmail.com",
    latestWork: {
      title: "Latest work: CodeIntellect",
      href: "https://drive.google.com/file/d/1M7IAAqdmXa3HPyzMt-RB90UEvGe3jr8c/view?usp=sharing",
      videoSrc: "/Codeintellect_demo_main.mp4",
    },
    links: [
      {
        title: "LeetCode",
        description: "Solved problems and coding progress",
        href: "https://leetcode.com/u/eashanjoshi/",
      },
      {
        title: "GeeksForGeeks",
        description: "Institute leaderboard rank #6",
        href: "https://www.geeksforgeeks.org/user/eashanj4/",
      },
      {
        title: "Strava",
        description: "Runs, rides, and weekly training",
        href: "https://www.strava.com/athletes/170749275",
      },
    ],
  },
  experience: [
    {
      company: "Tradeify",
      position: "Senior Full Stack Engineer",
      startDate: "May 2026",
      endDate: "Present",
      location: "Miami, USA",
      summary: [
        "Built the crypto trader frontend using Next.js, TypeScript, Material UI, Redux Toolkit, and TanStack Query, migrating dashboard, checkout, billing, payouts, journal, and affiliate workflows into a unified design system across 25+ pages.",
        "Led the Worthy-to-BridgerPay migration by identifying PCI-DSS risks in raw-card handling and designing a provider-agnostic tokenization layer that enabled integration with zero downstream call-site changes.",
        "Drove QA validation of the crypto admin console, root-causing a full-environment API outage to missing database migrations and documenting 20+ permission, configuration, and incomplete-endpoint defects before launch.",
        "Developed Python risk-exposure calculations and Celery automation workflows for the futures backend, supporting automated risk processing and scheduled backend operations.",
        "Authored frontend and backend architecture documentation covering API integration and environment setup; consolidated 8 duplicated payment-input implementations into a reusable component to improve maintainability and onboarding.",
      ],
    },
    {
      company: "Chime",
      position: "Software Developer",
      startDate: "May 2025",
      endDate: "May 2026",
      location: "Remote, USA",
      summary: [
        "Worked on Smart Finance Assistant project for Chime using AWS Lex and Polly for NLP and text-to-speech capabilities, delivering personalized banking insights. Collaborated with Product, Data Science, and Compliance teams through requirement-gathering and design workshops.",
        "Built secure backend microservices, TransactionService and AccountService, in Python (FastAPI, Flask) with PostgreSQL and Redis caching. Integrated UserProfile API and Payments API via RESTful endpoints for low-latency processing, optimizing performance with architecture teams.",
        "Created an interactive React Native dashboard using Redux Toolkit and React Query to monitor model accuracy, engagement metrics, and conversation flows. Worked with product analysts and UX teams to translate insights into improved user experiences.",
        "Implemented enterprise-grade authentication and authorization using AWS Cognito and JWT-based RBAC. Integrated SSO for internal tools while ensuring SOC 2, PCI-DSS, and FAPI compliance with security teams.",
        "Developed CI/CD pipelines with GitHub Actions and Jenkins, added static code analysis using SonarQube, and ran automated testing with Pytest, Jacoco, and Cypress. Coordinated with DevOps to maintain consistent deployment standards and code quality.",
        "Containerized microservices using Docker, deployed on AWS EKS with Helm charts, enabling event-driven architecture with Kafka. Implemented Prometheus and Grafana for observability, collaborating with SRE and platform teams to maintain reliability.",
      ],
    },
    {
      company: "Morningstar India Pvt. Ltd.",
      position: "Software Engineer",
      startDate: "Aug 2020",
      endDate: "Jul 2022",
      location: "MH, India",
      summary: [
        "Developed enterprise financial-data systems using Python and Flask, streamlining global data workflows and reducing API response time by 35%, team up with cross-functional stakeholders to deliver, secure Azure-based backend services for Morningstar’s investment research platform.",
        "Built Python microservices using Flask, FastAPI, Celery, and Redis for data ingestion, validation, authentication, and logging, enhancing modularity and scalability, while boosting feature delivery speed and enabling Morningstar to efficiently manage high-volume financial datasets.",
        "Designed and maintained diverse APIs including REST, SOAP, internal microservices, and Azure Function APIs, enabling seamless investor insights, client dashboards, and mobile integrations, improving data accuracy, availability, and reducing manual intervention by 50% across platforms.",
        "Developed React.js front-ends for investment-analytics dashboards and user-reporting tools, integrating with backend services. Improved UI responsiveness and performance, increasing user engagement by 30% and reducing support tickets by 25%, enhancing the overall client experience.",
        "Authored optimized, secure Oracle SQL and PL/SQL queries to support high-volume financial transactions. Implemented indexing, encryption, and query optimization strategies on Azure SQL, reducing latency by 45% and ensuring compliance with PII and regulatory standards.",
        "Led testing efforts with pytest, Postman, Selenium, and JMeter, implementing automated pipelines via Azure DevOps. Achieved 90% test coverage, reduced QA cycle time by 35%, and ensured system stability for production-ready financial analytics services.",
        "Collaborated with DevOps on secure deployments using Docker, Helm, and Azure DevOps, overseeing release validation, rollback planning, and infrastructure provisioning, contributing to 99.9% uptime across QA, staging, and production environments for Morningstar’s platforms.",
      ],
    },
    {
      company: "Yardi Software India Pvt. Ltd.",
      position: "Software Engineer",
      startDate: "Jun 2019",
      endDate: "Jul 2020",
      location: "MH, India",
      summary: [
        "Developed and maintained over 80 scalable backend components using Python and PostgreSQL, enhancing multi-tenant accounting operations for insurance, tax, and escrow workflows in high-availability production environments.",
        "Built RESTful APIs integrating backend systems with React-based frontends, ensuring seamless, secure, and efficient data exchange across fiduciary, compliance, and trust accounting modules for enterprise clients.",
        "Automated complex accounting workflows using Python, Redis, and schema-based validation logic, reducing manual operational effort by 60+ hours monthly and improving overall data accuracy and process integrity by 15%.",
        "Partnered with QA teams to design unit and integration test suites, increasing automated test coverage, reducing defect turnaround by 50%, and ensuring higher reliability and stability across production trust accounting systems.",
        "Leveraged PySpark and Kafka to optimize financial ETL processes, improving batch job reliability, data pipeline performance, and real-time reporting capabilities for large-scale periodic financial data processing workflows.",
      ],
    },
  ],
  projects: [
    {
      name: "CodeIntellect - Multi-Agent AI Systems Lab",
      summary:
        "Built a Python, FastAPI, and React platform leveraging a multi-agent AI system for automated code debugging, critique, and ML leakage checks. Integrated this system within a stateless, containerized EKS pipeline for processing code at scale. Added logging and Excel exports for full auditability across 120+ code sessions. Reduced manual debugging by ~2 hours/session through intelligent agent collaboration and classification.",
      bullets: [
        "Deployed multi-agent AI architecture",
        "120+ debug sessions",
        "Excel log exports",
      ],
      tech: [
        "Python",
        "FastAPI",
        "React",
        "Docker",
        "AWS (S3, EKS)",
        "GPT-4",
        "LLMs",
      ],
      linkPreview:
        "https://drive.google.com/file/d/1M7IAAqdmXa3HPyzMt-RB90UEvGe3jr8c/view?usp=sharing",
      linkSource:
        "https://drive.google.com/file/d/1M7IAAqdmXa3HPyzMt-RB90UEvGe3jr8c/view?usp=sharing",
      previewLabel: "View demo",
      sourceLabel: "Demo & notes",
    },
    {
      name: "Graph-Based Analysis of the Maven Central Ecosystem",
      summary:
        "Performed large-scale graph analytics on 15M+ Maven package releases using Cypher and Neo4j to study dependency evolution, versioning cadence, and ecosystem risk patterns in open-source Java libraries, with ongoing GraphRAG integration for natural language insights. Paper accepted at IEEE IC_ETC 2025.",
      bullets: [
        "Queried 130M+ dependency edges",
        "Computed metrics via Goblin & Weaver",
        "Extending to GraphRAG interface",
      ],
      tech: [
        "Python",
        "CUDA",
        "Cypher",
        "Neo4j",
        "GraphRAG",
        "Weaver API",
        "Graph Theory",
        "Open Source",
      ],
      linkPreview:
        "https://drive.google.com/file/d/1JtBgr1S6ZlkuFrPmkicmcwhi-oORWC26/view?usp=sharing",
      linkSource:
        "https://github.com/EashanJoshi/Graph-Based-Analysis-of-the-Maven-Central-Ecosystem",
      previewLabel: "View paper",
      sourceLabel: "Source",
    },
    {
      name: "Detecting and Recommending Fixes for Multi-Test Data Leakage in Machine Learning Pipelines",
      summary:
        "Built a Python-based tool to detect multi-test leakage in machine learning workflows, enhancing model reliability by flagging common pipeline flaws like preprocessing before train-test split. Currently working on version 1.2 which will integrate LLMs (via GPT-4) to generate context-aware fix suggestions and automate corrections.",
      bullets: [
        "Flags leakage patterns",
        "Suggests fix strategies",
        "v1.2: LLM-powered auto-fixes",
      ],
      tech: ["Python", "GPT-4", "LLMs", "Scikit-learn"],
      linkPreview:
        "https://drive.google.com/file/d/1NOMVlR8y-azXHbp6_6LHglqu63hR70_g/view?usp=sharing",
      linkSource: "https://github.com/EashanJoshi/DataLeakage",
      previewLabel: "View write-up",
      sourceLabel: "Source",
    },
    {
      name: "Information Retrieval with Vector Embeddings for Bugzilla Reports",
      summary:
        "Developed a full-stack pipeline to measure CRM ticket and bug report similarity using BM25, LDA+GloVe, and Siamese CNNs across Eclipse, Firefox, and Mobile datasets.",
      bullets: [
        "Preprocessed bug report data",
        "Applied BM25 & LDA+GloVe",
        "Trained domain-specific Siamese CNN",
      ],
      tech: ["Python", "TensorFlow", "GloVe", "BM25", "LDA"],
      linkPreview:
        "https://drive.google.com/file/d/15HPCIsCgWop5m4rl_o_VZLyoW1ppQsQR/view?usp=sharing",
      linkSource:
        "https://github.com/EashanJoshi/Duplicate-Bug-Report-Detection-using-Siamese-Convolutional-Neural-Network",
      previewLabel: "View write-up",
      sourceLabel: "Source",
    },
    {
      name: "Options Pricing Models",
      summary:
        "Implements advanced pricing models for European and American call options with live data, sensitivity analysis, and ML predictions—designed for robust quantitative finance analysis.",
      bullets: [
        "Black-Scholes, binomial trees",
        "Live market data feed",
        "ML-based volatility prediction",
      ],
      tech: ["Python", "yfinance", "Black-Scholes", "binomial trees", "Greeks"],
      linkPreview: "https://github.com/EashanJoshi/Options-Pricing-Models",
      linkSource: "https://github.com/EashanJoshi/Options-Pricing-Models",
      previewLabel: "View repo",
      sourceLabel: "Source",
    },
  ],
  about: {
    paragraphs: [
      "Hi, I’m Eashan Joshi—a Software Engineer and AI researcher passionate about building intelligent, high-performance systems. I hold a Master’s in Data Science from Rochester Institute of Technology (May 2025) and a Bachelor’s in Computer Engineering from Pune Institute of Computer Technology.",
      "My work sits at the intersection of software engineering and AI: multi-agent LLM systems like CodeIntellect, RAG and vector-search pipelines, GraphRAG research on Maven Central (IEEE ICETC 2025), and production backends across fintech and enterprise platforms at Tradeify, Chime, Morningstar, and Yardi.",
      "I specialize in scalable services, LLM-integrated tools, and cloud-native infrastructure—using stacks like LangChain, FastAPI, Neo4j, CUDA, PySpark, and AWS/Azure. Outside of tech, I’m a fitness enthusiast and endurance athlete who stays curious through health science podcasts.",
    ],
    image: "/eashan-big.jpg",
  },
  skills: [
    {
      title: "Languages",
      items: [
        "Python",
        "Java",
        "JavaScript",
        "TypeScript",
        "Kotlin",
        "SQL",
        "C++",
        "C#",
        "Go",
        "R",
        "HTML5",
        "CSS3",
      ],
    },
    {
      title: "Frontend",
      items: [
        "React",
        "React Native",
        "Redux Toolkit",
        "React Query",
        "Angular",
        "Vue.js",
        "Tailwind CSS",
        "Bootstrap",
      ],
    },
    {
      title: "Backend",
      items: [
        "FastAPI",
        "Flask",
        "Django",
        "Node.js",
        "Express.js",
        "Spring Boot",
        "Celery",
        "REST APIs",
        "SOAP",
        "GraphQL",
        "Microservices",
      ],
    },
    {
      title: "AI & Machine Learning",
      items: [
        "LLMs",
        "Multi-agent systems",
        "LangChain",
        "LlamaIndex",
        "LangGraph",
        "RAG",
        "GraphRAG",
        "OpenAI APIs",
        "GPT models",
        "LLaMA",
        "Claude",
        "TensorFlow",
        "PyTorch",
        "scikit-learn",
        "NLP",
        "BERT",
        "RoBERTa",
        "spaCy",
        "Vector embeddings",
        "Pinecone",
        "FAISS",
        "Prompt engineering",
        "Model Context Protocol",
        "CUDA",
      ],
    },
    {
      title: "Cloud & DevOps",
      items: [
        "AWS",
        "EKS",
        "S3",
        "Lambda",
        "API Gateway",
        "Cognito",
        "Fargate",
        "CloudWatch",
        "X-Ray",
        "CodePipeline",
        "CodeBuild",
        "Azure",
        "AKS",
        "Azure DevOps",
        "GCP",
        "Docker",
        "Kubernetes",
        "Helm",
        "Terraform",
        "Ansible",
        "Jenkins",
        "GitHub Actions",
        "GitLab CI/CD",
        "CI/CD pipelines",
      ],
    },
    {
      title: "Data & Messaging",
      items: [
        "PostgreSQL",
        "MySQL",
        "MongoDB",
        "Cassandra",
        "Redis",
        "Apache Kafka",
        "Apache Flink",
        "Apache Spark",
        "PySpark",
        "Neo4j",
        "Elasticsearch",
        "Oracle SQL",
        "PL/SQL",
        "Firebase",
      ],
    },
    {
      title: "Testing & Observability",
      items: [
        "Pytest",
        "JUnit",
        "TestNG",
        "Mockito",
        "Cypress",
        "Selenium",
        "Postman",
        "Swagger",
        "SonarQube",
        "JaCoCo",
        "JMeter",
        "Prometheus",
        "Grafana",
      ],
    },
    {
      title: "Architecture & Engineering",
      items: [
        "Event-driven architecture",
        "Serverless architecture",
        "Domain-driven design",
        "MVC",
        "Repository pattern",
        "Dependency injection",
        "Design patterns",
        "Distributed systems",
        "API design",
        "Secure authentication",
        "JWT",
        "RBAC",
        "SSO",
      ],
    },
    {
      title: "Certifications",
      items: [
        "AWS Certified Cloud Practitioner",
        "AWS Certified Developer – Associate",
      ],
    },
  ],
  resume: {
    description:
      "Want the full picture of my experience and qualifications? View my latest resume.",
    href: "/Eashan_Joshi_Resume.pdf",
    label: "View my resume",
  },
  contact: {
    heading: "Let’s Connect",
    description: "Reach out for collaboration, questions, or just to say hi.",
    links: [
      {
        label: "Email",
        href: "mailto:eashan.m.joshi@gmail.com",
        icon: "email",
      },
      {
        label: "GitHub",
        href: "https://github.com/EashanJoshi",
        icon: "github",
        external: true,
      },
      {
        label: "LinkedIn",
        href: "https://www.linkedin.com/in/eashanjoshi/",
        icon: "linkedin",
        external: true,
      },
      {
        label: "Instagram",
        href: "https://www.instagram.com/eashan_joshi11/",
        icon: "instagram",
        external: true,
      },
    ],
  },
};
